site_name: Amazon EKS Blueprints Quick Start
repo_name: "aws-quickstart/cdk-eks-blueprints"
repo_url: "https://github.com/aws-quickstart/cdk-eks-blueprints"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Getting Started: 'getting-started.md'
  - Multi-Cluster Management: 'cluster-management.md'
  - Core Concepts: 'core-concepts.md'
  - OPA Gatekeeper: 'opa-gatekeeper.md'
  - Teams: 
    - Teams: 'teams/teams.md'
    - EMR on EKS Team: 'teams/emr-eks-team.md'
    - AWS Batch on EKS Team: 'teams/aws-batch-on-eks-team.md'
  - Pipelines: 'pipelines.md'
  - AddOns:
    - Overview: 'addons/index.md'
    - ACK: 'addons/ack-addon.md'
    - ADOT: 'addons/adot-addon.md'
    - AMP ADOT: 'addons/amp-addon.md'
    - AWS App Mesh: 'addons/app-mesh.md'
    - Apache Airflow: 'addons/apache-airflow.md'
    - AWS Batch for EKS: 'addons/aws-batch-on-eks.md'
    - ArgoCD: 'addons/argo-cd.md'
    - AWS For Fluent Bit: 'addons/aws-for-fluent-bit.md'
    - AWS Load Balancer Controller: 'addons/aws-load-balancer-controller.md'
    - AWS Node Termination Handler: 'addons/aws-node-termination-handler.md'
    - AWS Private CA Issuer: 'addons/aws-privateca-issuer.md'
    - Backstage: 'addons/backstage.md'
    - Calico: 'addons/calico.md'
    - Calico Operator: 'addons/calico-operator.md'
    - Certificate Manager: 'addons/cert-manager.md'
    - CloudWatch ADOT: 'addons/cloudwatch-adot-addon.md'
    - Cluster Autoscaler: 'addons/cluster-autoscaler.md'
    - Container Insights: 'addons/container-insights.md'
    - CoreDns: 'addons/coredns.md'
    - Datadog: 'addons/datadog.md'
    - Dynatrace: 'https://github.com/dynatrace-oss/dynatrace-eks-blueprints-addon'
    - EBS CSI Driver: 'addons/ebs-csi-driver.md'
    - EFS CSI Driver: 'addons/efs-csi-driver.md'
    - External DNS: 'addons/external-dns.md'
    - External Secrets: 'addons/external-secrets.md'
    - EMR on EKS: 'addons/emr-eks.md'
    - FluxCD: 'addons/fluxcd.md'
    - NVIDIA GPU Operator: 'addons/gpu-operator.md'
    - Grafana Operator: 'addons/grafana-operator.md'
    - IBM Instana: 'addons/instana-addon.md'
    - Istio Base: 'addons/istio-base.md'
    - Istio Control Plane: 'addons/istio-control-plane.md'
    - JupyterHub: 'addons/jupyterhub.md'
    - Karpenter: 'addons/karpenter.md'
    - Kasten: 'addons/kasten-k10.md'
    - Keda: 'addons/keda.md'
    - Keptn: 'https://github.com/keptn-sandbox/keptn-eks-blueprints-addon'
    - Knative: 'addons/knative-operator.md'
    - Komodor: 'https://github.com/komodorio/komodor-eks-blueprints-addon'
    - Kube Proxy: 'addons/kube-proxy.md'
    - Kubecost: 'addons/kubecost.md'
    - Kubeflow: 'addons/kubeflow.md'
    - Kubevious: 'addons/kubevious.md'
    - Kube State Metrics: 'addons/kube-state-metrics.md'
    - Metrics Server: 'addons/metrics-server.md'
    - New Relic: 'addons/newrelic.md'
    - Nginx: 'addons/nginx.md'
    - OPA Gatekeeper: 'addons/opa-gatekeeper.md'
    - Paralus: 'addons/paralus.md'
    - Pixie: 'addons/pixie.md'
    - Prometheus Node Exporter: 'addons/prometheus-node-exporter.md'
    - Rafay: 'addons/rafay.md'
    - Secrets Store: 'addons/secrets-store.md'
    - Snyk: 'https://github.com/snyk-partners/snyk-monitor-eks-blueprints-addon'
    - SSM Agent: 'addons/ssm-agent.md'
    - Upbound Universal Crossplane: 'addons/upbound-universal-crossplane.md'
    - Velero: 'addons/velero.md'
    - Vpc Cni: 'addons/vpc-cni.md'
    - AWS XRay: 'addons/xray.md'
    - AWS XRay ADOT: 'addons/xray-adot-addon.md'
  - Internal:
    - CodeBuild CI: 'internal/ci.md'
    - Input Validation Framework: 'internal/input-validations-framework-readme.md'
    - Readme: 'internal/readme-internal.md'
  - Cluster Providers:
    - Overview: 'cluster-providers/index.md'
    - Generic Cluster Provider: 'cluster-providers/generic-cluster-provider.md'
    - ASG Cluster Provider: 'cluster-providers/asg-cluster-provider.md'
    - MNG Cluster Provider: 'cluster-providers/mng-cluster-provider.md'
    - Fargate Cluster Provider: 'cluster-providers/fargate-cluster-provider.md'
    - Import Cluster Provider: 'cluster-providers/import-cluster-provider.md'
  - Resource Providers:
    - Overview: 'resource-providers/index.md'
    - AMP Resource Provider: 'resource-providers/amp-provider.md'
    - Certificate Resource Providers: 'resource-providers/certificate-providers.md'
    - EFS Resource Providers: 'resource-providers/efs-providers.md'
    - Hosted Zone Resource Providers: 'resource-providers/hosted-zone-providers.md'
    - IAM Role Resource Providers: 'resource-providers/iam-role-providers.md'
    - KMS Key Resource Providers: 'resource-providers/kms-key-providers.md'
    - S3 Bucket Resource Providers: 'resource-providers/s3-providers.md'
    - VPC Resource Providers: 'resource-providers/vpc-providers.md'
  - Builders:
    - Overview: 'builders/index.md'
    - Observability Builder: 'builders/observability-builder.md'
    - Windows Builder: 'builders/windows-builder.md'
    - GPU Builder: 'builders/gpu-builder.md'
  - Extensibility: 'extensibility.md'
  - API Reference: 'api'
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
